name: Go

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.22
        id: go
      - name: Get dependencies
        run: make get-dependencies

      - name: Ensure that all files are properly formatted
        run: |
          FILES=$(gofmt -s -l cmd pkg)
          if [ -n "${FILES}" ]; then
              printf "Following files are not formatted: \n%s" "$FILES"
              exit 1
          fi

      - name: Go vet
        run: make vet

      - name: Test building
        run: make build

      - name: Run tests
        run: make test
